FROM dreg.cloud.sdu.dk/ucloud-apps/conda:24.1.2.0

USER 0

## Install Redis
RUN apt-get update \
 && apt-get install -y --no-install-recommends redis-server \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN apt-get install -y gpg

## Install PostgreSQL
#RUN \ 
#echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list \
# && wget -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - \
# && bash -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" >> /etc/apt/sources.list.d/pgdg.list' \
RUN apt-get -y update \
 && apt-get install -y --no-install-recommends postgresql \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* \
 && pip install --no-cache-dir --upgrade pip \
 ## PostgreSQL adapter for Python
 && pip install --no-cache-dir psycopg2-binary

COPY --chown="$USERID":"$GROUPID" start_app.sh /usr/local/bin/start_app
COPY --chown="$USERID":"$GROUPID" wait-for-postgres.sh /usr/local/bin/wait-for-postgres

USER $USERID

## Install Airflow and sudo/pip requirements
## Python in conda is 3.10
## Handle configuration in start_app
ENV AIRFLOW_HOME="/work/Airflow"

#cncf-kubernetes and docker are removed from the default list
RUN pip install "apache-airflow[aiobotocore,amazon,async,celery,common-io,elasticsearch,fab,ftp,google,google-auth,graphviz,grpc,hashicorp,http,ldap,microsoft-azure,mysql,odbc,openlineage,pandas,postgres,redis,sendgrid,sftp,slack,snowflake,ssh,statsd,uv,virtualenv]==2.8.3" \
--constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.8.3/constraints-3.10.txt"

WORKDIR /work